# Generated by Django 4.1.4 on 2023-03-16 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'customer_ids',
            },
        ),
        migrations.CreateModel(
            name='CustomerPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_password', models.CharField(max_length=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customersdata.customerid')),
            ],
            options={
                'db_table': 'customer_passwords',
            },
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=150)),
                ('receiving_targeted_ads', models.BooleanField(default=False)),
                ('remote_last_used', models.CharField(max_length=30)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customersdata.customerid')),
            ],
            options={
                'db_table': 'customer_details',
            },
        ),
    ]
